In [58]:
import os 
import ssl
import urllib.request

ssl._create_default_https_context = ssl._create_unverified_context

ocorrencias = [2025, 2026]
pasta = "sample_data"

os.makedirs(pasta, exist_ok=True)

for ano in ocorrencias:
    url = f"https://servicos.dpf.gov.br/dadosabertos/SINARM_CSV/OCORRENCIAS/OCORRENCIAS_{ano}.csv"
    caminho_arquivo = f"{pasta}/{ano}.csv"

    if not os.path.exists(caminho_arquivo):
        print(f"Arquivo {ano} ainda não criado. \n Buscando...")
        urllib.request.urlretrieve(url, caminho_arquivo)
    else:
        print("Arquivo já existe")

Arquivo já existe
Arquivo já existe

In [59]:
import pandas as pd

dataframe_listas = []

for ano in ocorrencias: 
    caminho_arquivo = f"{pasta}/{ano}.csv"

    if not os.path.exists(caminho_arquivo):
        print(f"Nao foi encontrado arquivo para o caminho dado: {caminho_arquivo}")
        continue

    dataframe_temp = pd.read_csv(caminho_arquivo, encoding="latin1", sep=";")
    dataframe_temp['ANO_OCORRENCIA'] = ano
    dataframe_listas.append(dataframe_temp)

dataframe_completo = pd.concat(dataframe_listas, ignore_index=True)

def clean_data(df):
    df_limpo = df.copy()
    
    df_limpo.columns = df_limpo.columns.str.strip().str.lower().str.replace(' ', '_')
    
    df_limpo = df_limpo.dropna(how='all')
    
    df_limpo = df_limpo.drop_duplicates()
    
    colunas_texto = df_limpo.select_dtypes(include=['object']).columns
    for col in colunas_texto:
        df_limpo[col] = df_limpo[col].str.strip()
        
    return df_limpo

print("Dataframe shape antes limpeza", dataframe_completo.shape)

# dataframe_completo = clean_data(dataframe_completo)

print("Dataframe shape pós limpeza", dataframe_completo.shape)

display(dataframe_completo.head())

Dataframe shape antes limpeza (85851, 10)
Dataframe shape pós limpeza (85851, 10)

,ANO_OCORRENCIA,MES_OCORRENCIA,UF,MUNICIPIO,ESPECIE_ARMA,MARCA_ARMA,CALIBRE_ARMA,TIPO_OCORRENCIA,MAIS_1000_MIL_HAB,TOTAL
0,2025,1,AC,ACRELÂNDIA,Espingarda ...,ROSSI (AMADEO ROSSI S.A.) ...,36 ...,Apreensão de Arma de Fogo ...,N,1
1,2025,1,AC,CRUZEIRO DO SUL,Espingarda ...,ROSSI (AMADEO ROSSI S.A.) ...,28 ...,Extravio/Perda de Arma de Fogo ...,N,1
2,2025,1,AC,FEIJÓ,Espingarda ...,CBC (COMPANHIA BRASILEIRA DE CARTUCHOS) ...,28 ...,Extravio/Perda de Arma de Fogo ...,N,1
3,2025,1,AC,RIO BRANCO,Espingarda ...,ROSSI (AMADEO ROSSI S.A.) ...,36/.22LR (duplo cano) ...,Extravio/Perda de Arma de Fogo ...,S,2
4,2025,1,AC,RIO BRANCO,Pistola ...,TAURUS ARMAS S.A. ...,.380 ACP ...,Roubo de Arma de Fogo ...,S,1

In [ ]:
# dataframe_completo.to_csv(f"sample_data/dataset_limpo.csv", index=False, encoding='latin1', sep=';')
# dataframe_completo.to_parquet(f"sample_data/dataset_limpo.parquet", index=False)
import numpy as np
from sklearn.preprocessing import StandardScaler

# Preparando para clustering
def prepare_clustering(df):
    df_cluster = df.copy()

    if "MAIS_1000_MIL_HAB" in df_cluster:
        df_cluster["MAIS_1000_MIL_HAB"] = df_cluster["MAIS_1000_MIL_HAB"].map({"S": 1, "N": 0})
        df_cluster["MAIS_1000_MIL_HAB"] = df_cluster["MAIS_1000_MIL_HAB"].fillna(0)

    # Remover UF e municipio (nao são relevantes para clustering)
    if "UF" in df_cluster:
        df_cluster = df_cluster.drop(columns=["UF"])

    if "MUNICIPIO" in df_cluster:
        df_cluster = df_cluster.drop(columns=["MUNICIPIO"])

    # if "ANO_OCORRENCIA" in df_cluster:
    #     df_cluster["ANO_OCORRENCIA"] = df_cluster["ANO_OCORRENCIA"].map({2025: 1, 2026: 0})
    if "MES_OCORRENCIA" in df_cluster:
        df_cluster['MES_OCORRENCIA'] = pd.to_numeric(df_cluster['MES_OCORRENCIA'], errors='coerce') 
        df_cluster['mes_sin'] = np.sin(2 * np.pi * df_cluster['MES_OCORRENCIA'] / 12)
        df_cluster['mes_cos'] = np.cos(2 * np.pi * df_cluster['MES_OCORRENCIA'] / 12)
        df_cluster = df_cluster.drop('MES_OCORRENCIA', axis=1)

    alta_cardinalidade = ['CALIBRE_ARMA', 'MARCA_ARMA']
    for col in alta_cardinalidade:
        if col in df_cluster:
            freq = df_cluster[col].value_counts(normalize=True)
            df_cluster[f'{col}_freq'] = df_cluster[col].map(freq)
            df_cluster = df_cluster.drop(columns=[col])

    # fazendo hot encoding para as colunas restantes de baixa cardinalidade
    baixa_cardinalidade = ['TIPO_OCORRENCIA', 'ESPECIE_ARMA']
    baixa_cardinalidade = [col for col in baixa_cardinalidade if col in df_cluster.columns]

    df_cluster = pd.get_dummies(df_cluster, columns=baixa_cardinalidade, drop_first=True)

    for col in df_cluster.select_dtypes(include=['boolean']).columns:
        df_cluster[col] = df_cluster[col].astype(int)

    scaler = StandardScaler()

    cols_para_escalonar = ['ANO_OCORRENCIA', 'TOTAL', 'CALIBRE_ARMA_freq', 'MARCA_ARMA_freq']
    cols_para_escalonar = [col for col in cols_para_escalonar if col in df_cluster.columns]

    df_cluster[cols_para_escalonar] = scaler.fit_transform(df_cluster[cols_para_escalonar])

    df_cluster = df_cluster.fillna(0)

    return df_cluster

dataframe_completo_cp = dataframe_completo.copy()
dataframe_completo_cp.to_parquet(f"sample_data/dataset_limpo_antes_normalizacao.parquet", index=False)

dataframe_completo = prepare_clustering(dataframe_completo)
print("Dataframe shape antes preparação para clustering", dataframe_completo.shape)
display(dataframe_completo.head())
dataframe_completo.to_parquet(f"sample_data/dataset_limpo.parquet", index=False)

Dataframe shape antes preparação para clustering (85851, 35)

,ANO_OCORRENCIA,MAIS_1000_MIL_HAB,TOTAL,mes_sin,mes_cos,CALIBRE_ARMA_freq,MARCA_ARMA_freq,TIPO_OCORRENCIA_Alteração da Arma de Porte,TIPO_OCORRENCIA_Apostilada no Exercito,TIPO_OCORRENCIA_Apreensão de Arma de Fogo,...,ESPECIE_ARMA_Garrucha,ESPECIE_ARMA_Garruchao,ESPECIE_ARMA_Mosquetao,ESPECIE_ARMA_Outras especies,ESPECIE_ARMA_Pistola,ESPECIE_ARMA_Pistolao,ESPECIE_ARMA_Pistolete,ESPECIE_ARMA_Pistolete ou garruchao,ESPECIE_ARMA_Revolver,ESPECIE_ARMA_Rifle
0,-2.820119,0.0,-0.094003,0.5,0.866025,-0.567207,0.550080,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,-2.820119,0.0,-0.094003,0.5,0.866025,-0.389687,0.550080,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,-2.820119,0.0,-0.094003,0.5,0.866025,-0.389687,-0.210541,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,-2.820119,0.0,-0.022775,0.5,0.866025,-1.655791,0.550080,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,-2.820119,0.0,-0.094003,0.5,0.866025,-1.335655,1.202515,0,0,0,...,0,0,0,0,1,0,0,0,0,0